'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RandomStackGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g000uu0019
        '''g000uu0020
        '''g000uu0021
        '''g000uu0022
        '''g000uu8248
        '''g000uu0044
        '''g000uu0045
        '''g000uu0046
        '''g000uu0047
        '''g000uu8249
        '''g000uu0070
        '''g000uu0071
        '''g000uu0072
        '''g000uu0073
        '''g000uu8250
        '''g000uu0096
        '''g000uu0097
        '''g000uu0098
        '''g000uu0099
        '''g000uu8252
        '''g000uu8253
        '''g000uu8009
        '''g000uu8010
        '''g000uu8011
        '''g000uu8012
        '''g000uu8251
        '''.
        '''</summary>
        Friend ReadOnly Property ExcludeIDs() As String
            Get
                Return ResourceManager.GetString("ExcludeIDs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNIT_ID	UNIT_CAT	LEVEL	SUBRACE	BRANCH	SIZE_SMALL	ATTACK_ID	XP_KILLED	XP_NEXT	LEADERSHIP	WATER_ONLY	REACH
        '''g000uu0001	0	1	1	0	True	g000aa0001	20	80	0	False	3
        '''g000uu0002	0	2	1	0	True	g000aa0002	60	475	0	False	3
        '''g000uu0003	0	3	1	0	True	g000aa0003	120	950	0	False	3
        '''g000uu0004	0	2	1	0	True	g000aa0004	60	475	0	False	3
        '''g000uu0005	0	3	1	0	True	g000aa0005	115	950	0	False	3
        '''g000uu0006	0	1	1	1	True	g000aa0006	20	70	0	False	2
        '''g000uu0007	0	2	1	1	True	g000aa0007	60	500	0	False	2
        '''g000uu0008	0	1	1	2	True	g000aa0008	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestUnitsTable() As String
            Get
                Return ResourceManager.GetString("TestUnitsTable", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
