'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RandomStackGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID юнитов и минимальный размер стэка
        '''
        '''#темный эльф-гаст
        '''g000uu8144	3
        '''g000uu8044	3
        '''
        '''#ведьма
        '''g000uu0067	2
        '''#колдунья
        '''g000uu0068	3
        '''#суккуб
        '''g000uu0173	4
        '''#инкуб
        '''g000uu0065	4
        '''#якшини
        '''g000uu8156	4
        '''g000uu7532	4
        '''#привидение
        '''g000uu0078	2
        '''#призрак
        '''g000uu0079	2
        '''g000uu5279	2
        '''#эльф-призрак
        '''g000uu8267	3
        '''g001uu8267	3
        '''#тень
        '''g000uu0174	3
        '''
        '''#волхв
        '''g000uu8218	4
        '''g000uu8222	4
        '''#травница
        '''g000uu0033	2
        '''#посвященная
        '''g000uu0034	3
        '''#друид
        '''g000uu0035	3
        '''#ар [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BigStackUnits() As String
            Get
                Return ResourceManager.GetString("BigStackUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Соответствие между расами, ID рас в игре и ID столиц
        '''
        '''    G000FT0000HU0  H G000RR0000
        '''    G000FT0000DWC0 C G000RR0001
        '''    G000FT0000HE0  L G000RR0002
        '''    G000FT0000UN0  U G000RR0003
        '''    G000FT0000NE0  N G000RR0004
        '''    G000FT0000EL0  E G000RR0005
        '''.
        '''</summary>
        Friend ReadOnly Property Capitals() As String
            Get
                Return ResourceManager.GetString("Capitals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#файл, определяющий константы, используемые генератором
        '''#Параметр (без пробелов), значение (без пробелов), разделитель таб или пробел
        '''#слэш - перенос строки
        '''#если параметр не найден, используется заданный по умолчанию
        '''
        '''#Множитель для Сигмы в распределении Гаусса. Сигма=Множитель*Желаемое_значение
        '''defaultSigma				0.1
        '''
        '''#В заданном радиусе от столицы уменьшается множитель силы юнитов и стоимости лута, задаваемый в регенерторе
        '''#в зависимости от расстояния  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Constants() As String
            Get
                Return ResourceManager.GetString("Constants", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''//Location					$empty
        '''
        '''AppearanceChance	1.0
        '''
        '''RaceCities	Nothing
        '''
        '''AverageRadius			17
        '''
        '''maxEccentricityDispersion	0
        '''
        '''maxRadiusDispersion		0
        '''
        '''DecorationsAmount		0.75
        '''
        '''maxGoldMines			0	0
        '''maxManaSources			0	0
        '''maxCities			0
        '''maxVendors			0
        '''maxMercenaries		0
        '''maxMages			0
        '''maxTrainers			0
        '''maxRuins			0
        '''
        '''minStackToStackDist		5.0
        '''
        '''expAmount			1000
        '''
        '''mageSpellsMaxLevel		2
        '''mageSpellsMinLevel		1
        '''mageSpellsCount			4
        '''mageGlobalSpellsEnabled	False
        '''
        '''mercenariesMaxExpBar		1900
        '''mercenariesMinExpBar		1000
        '''mercenariesCount		4
        '''
        '''merc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property emptyloc() As String
            Get
                Return ResourceManager.GetString("emptyloc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map generator by Norvezskaya Semga
        '''
        '''#строка, начинающаяся с решетки, игнорируется
        '''#параметры и их значения не чувствительны к регистру
        '''#разделитель - пробел или табуляция (может идти несколько подряд)
        '''
        '''#внутри блоков настройки могут идти в любом порядке
        '''#порядок блоков тоже может быть любым с одним исключением:
        '''#блоки Location для расовых локаций должны стоять выше, чем блоки для обычных локаций (независимо от genMode)
        '''
        '''#если в блоке Location параметр имеет два значения, то при генерации будет выб [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property example_template_1() As String
            Get
                Return ResourceManager.GetString("example_template_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map generator by Norvezskaya Semga
        '''
        '''#строка, начинающаяся с решетки, игнорируется
        '''#параметры и их значения не чувствительны к регистру
        '''#разделитель - пробел или табуляция (может идти несколько подряд)
        '''
        '''#внутри блоков настройки могут идти в любом порядке
        '''#порядок блоков тоже может быть любым с одним исключением:
        '''#блоки Location для расовых локаций должны стоять выше, чем блоки для обычных локаций (независимо от genMode)
        '''
        '''#если в блоке Location параметр имеет два значения, то при генерации будет выб [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property example_template_2_symm() As String
            Get
                Return ResourceManager.GetString("example_template_2_symm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map generator by Norvezskaya Semga
        '''
        '''#строка, начинающаяся с решетки, игнорируется
        '''#параметры и их значения не чувствительны к регистру
        '''#разделитель - пробел или табуляция (может идти несколько подряд)
        '''
        '''#внутри блоков настройки могут идти в любом порядке
        '''#порядок блоков тоже может быть любым с одним исключением:
        '''#блоки Location для расовых локаций должны стоять выше, чем блоки для обычных локаций (независимо от genMode)
        '''
        '''#если в блоке Location параметр имеет два значения, то при генерации будет выб [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property example_template_2_unsymm() As String
            Get
                Return ResourceManager.GetString("example_template_2_unsymm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID юнитов
        '''#лидеры империи
        '''g000uu0019
        '''g000uu0020
        '''g000uu0021
        '''g000uu0022
        '''g000uu8248
        '''#лидеры кланов
        '''g000uu0044
        '''g000uu0045
        '''g000uu0046
        '''g000uu0047
        '''g000uu8249
        '''#лидеры легионов
        '''g000uu0070
        '''g000uu0071
        '''g000uu0072
        '''g000uu0073
        '''g000uu8250
        '''#лидеры нежити
        '''g000uu0096
        '''g000uu0097
        '''g000uu0098
        '''g000uu0099
        '''g000uu8252
        '''g000uu8253
        '''#лидеры эльфов
        '''g000uu8009
        '''g000uu8010
        '''g000uu8011
        '''g000uu8012
        '''g000uu8251
        '''
        '''#стражи столиц
        '''g000uu3001
        '''g000uu3002
        '''g000uu3003
        '''g000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExcludeIDs() As String
            Get
                Return ResourceManager.GetString("ExcludeIDs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID юнитов
        '''#последователь
        '''g000uu8276
        '''#уста богов
        '''g000uu2024
        '''g000uu8277
        '''#божественная длань
        '''g000uu8278
        '''#избранник богов
        '''g000uu8298
        '''g001uu8298
        '''#каратель
        '''g000uu7560
        '''g001uu7560
        '''#мастер культа
        '''g000uu7585
        '''g001uu7585
        '''.
        '''</summary>
        Friend ReadOnly Property ExcludeIDs_ModLore() As String
            Get
                Return ResourceManager.GetString("ExcludeIDs_ModLore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID юнитов
        '''#дрега зул
        '''g000uu6021
        '''g000uu6121
        '''#принцесса яата&apos;халли
        '''g000uu6006
        '''g000uu6106
        '''#юбер де лали
        '''g000uu6008
        '''g000uu6108
        '''#эрхог темная
        '''g000uu6009
        '''g000uu6109
        '''#утер
        '''g000uu6020
        '''g000uu6120
        '''#темный эльф лиф
        '''g000uu6007
        '''g000uu6107
        '''#утер второй
        '''g000uu6001
        '''g000uu6101
        '''#некромант эрхог
        '''g000uu6019
        '''g000uu6119
        '''#нидхегг
        '''g000uu6010
        '''g000uu6110
        '''#маг хугин
        '''g000uu6005
        '''g000uu6105
        '''#демон утер
        '''g000uu6002
        '''g000uu6102
        '''#астарот
        '''g000uu6011
        '''g000uu6111 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExcludeIDs_VanillaLore() As String
            Get
                Return ResourceManager.GetString("ExcludeIDs_VanillaLore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #волк
        '''g000uu5039
        '''g000uu5139
        '''#псина
        '''g000uu7533
        '''g006uu1030
        '''#снежный волк
        '''g000uu8296
        '''g004uu5039
        '''#белый волк
        '''g000uu7571
        '''g001uu7571
        '''#чумной волк
        '''g000uu8279
        '''g001uu8279
        '''#дух волка
        '''g000uu8005
        '''g000uu8105
        '''#вор
        '''g000uu0023
        '''g000uu0048
        '''g000uu0074
        '''g000uu0100
        '''g000uu8013
        '''g001uu0023
        '''g001uu0048
        '''g001uu0074
        '''g001uu0100
        '''g001uu8013
        '''g000uu5300
        '''g000uu5301
        '''g000uu5302
        '''g000uu5303
        '''g000uu5304
        '''#головорез
        '''g000uu5031
        '''g000uu5131
        '''#разбойник
        '''g000uu5030
        '''g000uu5130
        '''#крестьянин
        '''g000uu5001
        '''g000uu5101
        '''#тол [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExcludeIDsForNames() As String
            Get
                Return ResourceManager.GetString("ExcludeIDsForNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''genMode genMode = 1 Common_map_settings block and two Location blocks will be used - for starting and all other locations, respectively/ngenMode = 2 Common_map_settings block and all Location blocks will be used - individual settings for each location
        '''
        '''
        '''nRaces Number of races
        '''
        '''PlayersRaces Player races. Different and playable. Delimiter - ; (H;U;L;E;C;R or Humans;Undead;Legions;Elves;Clans;Random)/nIn this case, the first race in the list will be on the first location, the second on the second, etc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GenParametersDescription_Eng() As String
            Get
                Return ResourceManager.GetString("GenParametersDescription_Eng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''genMode			genMode=1 Будет использован блок Common_map_settings и два блока Location - для стартовых и всех остальных локаций, соответственно/ngenMode=2 Будет использован блок Common_map_settings и все блоки Location - для каждой локации индивидуальные настройки
        '''
        '''
        '''nRaces			Количество рас
        '''
        '''PlayersRaces	Расы игроков. Разные и играбельные. Разделитель - ; (H;U;L;E;C;R или Humans;Undead;Legions;Elves;Clans;Random)/nПри этом первая раса в списке будет на первой локации, вторая - на второй, и т.д./nЕсли р [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GenParametersDescription_Rus() As String
            Get
                Return ResourceManager.GetString("GenParametersDescription_Rus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''ReadFromFile	[Common_map_settings:Location:Nonhideable]	[String] &quot;&quot; &quot;&quot;
        '''
        '''genMode	[Creation_settings:Nonhideable]	[Integer]	1	2
        '''
        '''nRaces	[Common_map_settings]	[Integer]	2	4
        '''
        '''#[Humans;Undead;Legions;Elves;Clans;Random]
        '''PlayersRaces	[Common_map_settings]	[StringArray]%;	[Nothing]%[H;U;L;E;C;R]
        '''
        '''StartGold	[Common_map_settings]	[Integer]	0	9999
        '''StartMana	[Common_map_settings]	[Integer]	0	9999
        '''
        '''SpellsMaxLevel	[Common_map_settings]	[Integer]	1	5
        '''
        '''ApplySymmetry	[Common_map_settings]	[Boolean]	False	Tr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GenParametersRange() As String
            Get
                Return ResourceManager.GetString("GenParametersRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Идентификаторы типов предметов.
        '''0	nonattack_artifact
        '''1	relic
        '''2	attack_artifact
        '''3	banner
        '''4	elixir
        '''5	healing_elixir
        '''6	ressurection_elixir
        '''7	permanent_elixir
        '''8	scroll
        '''9	stuff
        '''10	jewel
        '''11	sphere
        '''12	talisman
        '''13	boots
        '''14	special
        '''.
        '''</summary>
        Friend ReadOnly Property Items() As String
            Get
                Return ResourceManager.GetString("Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Идентификаторы предметов и множители шанса появления предмета.
        '''#эльфийские сапоги
        '''G000IG1010	0.33
        '''#мешочек трав
        '''G001IG0180	0.2
        '''#талисман скваера
        '''G000IG9101	0.2
        '''#клыкастая связка
        '''G001IG0082	0.1
        '''
        '''#Эликсир защиты от магии Воздуха
        '''G000IG0021	1.4
        '''#Эликсир защиты от магии Воды
        '''G000IG0022	1.4
        '''#Эликсир защиты от магии Земли
        '''G000IG0023	1.4
        '''#Эликсир защиты от магии Огня
        '''G000IG0024	1.4
        '''#Эликсир защиты от магии Смерти
        '''G001IG0036	1.4
        '''#Эликсир защиты от  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LootItemChanceMultiplier() As String
            Get
                Return ResourceManager.GetString("LootItemChanceMultiplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g000LR0001	H
        '''g000LR0002	H
        '''g000LR0003	H
        '''g000LR0004	C
        '''g000LR0005	C
        '''g000LR0006	C
        '''g000LR0007	L
        '''g000LR0008	L
        '''g000LR0009	L
        '''g000LR0010	U
        '''g000LR0011	U
        '''g000LR0012	U
        '''g000LR0016	E
        '''g000LR0017	E
        '''g000LR0018	E
        '''.
        '''</summary>
        Friend ReadOnly Property Lords() As String
            Get
                Return ResourceManager.GetString("Lords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Первый столбец - идентификаторы объектов.
        '''#В остальных - допустимые места расстановки объектов и расы
        '''
        '''#здания
        '''g000mg0001	G	H C E N S		%religious% %natural%
        '''g000mg0002	G	C				%building%
        '''g000mg0003	G	H N S			%building%
        '''g000mg0004	G	L				%building% %natural%
        '''g000mg0005	G	L				%building% %natural%
        '''
        '''#водопады
        '''#g000mg0006	G	H L C U E N S
        '''#g000mg0007	G	H L C U E N S
        '''
        '''#плато
        '''#g000mg0008	G	H L C U E N S
        '''#g000mg0009	G	H L C U E N S
        '''#g000mg0010	G	H L C  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MapObjectRace() As String
            Get
                Return ResourceManager.GetString("MapObjectRace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gold.
        '''</summary>
        Friend ReadOnly Property mineTypeGold() As String
            Get
                Return ResourceManager.GetString("mineTypeGold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to randmana.
        '''</summary>
        Friend ReadOnly Property mineTypeRandomMana() As String
            Get
                Return ResourceManager.GetString("mineTypeRandomMana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t1mana.
        '''</summary>
        Friend ReadOnly Property mineTypeT1Mana() As String
            Get
                Return ResourceManager.GetString("mineTypeT1Mana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t3mana.
        '''</summary>
        Friend ReadOnly Property mineTypeT3Mana() As String
            Get
                Return ResourceManager.GetString("mineTypeT3Mana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID объекта, в остальных столбцах возможные названия
        '''#разделитель - _
        '''.
        '''</summary>
        Friend ReadOnly Property ObjectsText_Eng() As String
            Get
                Return ResourceManager.GetString("ObjectsText_Eng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID объекта, в остальных столбцах возможные названия
        '''#разделитель - _
        '''
        '''#лорды Humans Clans Legions Undead Elvens (имена доллжны походить как девочкам, так и мальчикам. За исключением Кланов)
        '''g000LR0001_Алексис_Лотай_Келли_Моар_Дориа
        '''g000LR0002_Алексис_Лотай_Келли_Моар_Дориа
        '''g000LR0003_Алексис_Лотай_Келли_Моар_Дориа
        '''g000LR0004_Орхтар_Дархорд_Фуррт_Бордольт_Неромт
        '''g000LR0005_Орхтар_Дархорд_Фуррт_Бордольт_Неромт
        '''g000LR0006_Орхтар_Дархорд_Фуррт_Бордольт_Не [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ObjectsText_Rus() As String
            Get
                Return ResourceManager.GetString("ObjectsText_Rus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000MAGE.
        '''</summary>
        Friend ReadOnly Property objKeyMage() As String
            Get
                Return ResourceManager.GetString("objKeyMage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000MERC.
        '''</summary>
        Friend ReadOnly Property objKeyMercenaries() As String
            Get
                Return ResourceManager.GetString("objKeyMercenaries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000MERH.
        '''</summary>
        Friend ReadOnly Property objKeyMerchant() As String
            Get
                Return ResourceManager.GetString("objKeyMerchant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MOMNE.
        '''</summary>
        Friend ReadOnly Property objKeyMountain() As String
            Get
                Return ResourceManager.GetString("objKeyMountain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000RU.
        '''</summary>
        Friend ReadOnly Property objKeyRuin() As String
            Get
                Return ResourceManager.GetString("objKeyRuin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000FT0000.
        '''</summary>
        Friend ReadOnly Property objKeyTown() As String
            Get
                Return ResourceManager.GetString("objKeyTown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000TRAI.
        '''</summary>
        Friend ReadOnly Property objKeyTrainer() As String
            Get
                Return ResourceManager.GetString("objKeyTrainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Первый столбец - идентификаторы объектов.
        '''#В остальных - как скреплять объекты
        '''#U = 1/-1 1/0
        '''#D = 1/2 1/3
        '''#L = -1/1 0/1
        '''#R = 2/1 3/1
        '''#B - должна быть граница карты (указывается только одна точка, которая не находится в углу объекта)
        '''#UB = 1/0
        '''#DB = 1/2
        '''#LB = 0/1
        '''#RB = 2/1
        '''#W = водопад
        '''
        '''#обычные
        '''g000mg0008	U L
        '''g000mg0010	L R
        '''g000mg0013	U D
        '''g000mg0060	D R
        '''g000mg0063	U L
        '''
        '''#затычки
        '''g000mg0009	R
        '''g000mg0011	L
        '''g000mg0061	U
        '''g000mg0062	D
        '''g000mg [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PlateauConstructor() As String
            Get
                Return ResourceManager.GetString("PlateauConstructor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Список играбельных субрас
        ''' 
        '''#империя
        '''1
        '''#нежить
        '''2
        '''#легионы
        '''3
        '''#кланы
        '''4
        '''#эльфы
        '''14
        '''.
        '''</summary>
        Friend ReadOnly Property PlayableSubraces() As String
            Get
                Return ResourceManager.GetString("PlayableSubraces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID предметов, которые генератор должен оставлять на месте
        '''
        '''#Ржавые кандалы
        '''G000IG2007
        '''
        '''#Лютня очарования
        '''G000IG3022
        '''
        '''#Тиара чистоты
        '''G000IG2006
        '''
        '''#типы предметов
        '''special
        '''.
        '''</summary>
        Friend ReadOnly Property PreservedItems() As String
            Get
                Return ResourceManager.GetString("PreservedItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Идентификаторы рас.
        '''#В конце каждой строки ID, на который будут заменяться все остальные ID стртоки
        '''Humans			H	6	1
        '''Undead			U	2
        '''Legions			L	3
        '''Clans			C	K	4
        '''Elves			E	7	14
        '''Neutral			N	5
        '''Greenskins		G	O	8
        '''Dragons			D	9
        '''Swamp			S	10
        '''Water			W	11
        '''Barbarians		B	12
        '''Animals			A	13
        '''AnimalSpider	AS	15
        '''AnimalSnowTerr	AST	16
        '''AnimalWolf		AW	18
        '''AnimalGriffin	AG	19
        '''.
        '''</summary>
        Friend ReadOnly Property Races() As String
            Get
                Return ResourceManager.GetString("Races", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Идентификаторы рас. список возможных тэгов, через : - радиус подзоны
        '''
        '''H %natural%:4 %building%:4 %religious%:3 %marshes%:3 %graveyard%:2 %empbuilding%:4
        '''L %natural%:4 %building%:4 
        '''C %natural%:4 %building%:4 %religious%:2
        '''U %natural%:4 %building%:4							 %graveyard%:4					%undbuilding%:4 %undelfbuilding%:4
        '''E %natural%:4 %building%:4
        '''N %natural%:4 %building%:4 %religious%:3 %marshes%:4 %graveyard%:3
        '''S %natural%:4 %building%:3 %religious%:3 %marshes%:5        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RaceSublocations() As String
            Get
                Return ResourceManager.GetString("RaceSublocations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %default%.
        '''</summary>
        Friend ReadOnly Property readDefaultFileKeyword() As String
            Get
                Return ResourceManager.GetString("readDefaultFileKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %nomodlore%.
        '''</summary>
        Friend ReadOnly Property readMLoreFileKeyword() As String
            Get
                Return ResourceManager.GetString("readMLoreFileKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %novanillalore%.
        '''</summary>
        Friend ReadOnly Property readVLoreFileKeyword() As String
            Get
                Return ResourceManager.GetString("readVLoreFileKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID юнитов, которых в отряде должно быть по одному.
        '''#В каждой строке список юнитов, которые не должны появляться в одном отряде
        '''#волхв травница посвященная друид архидруид исса хэйсса ламия
        '''g000uu8218 g000uu8222 g000uu0033 g000uu0034 g000uu0035 g000uu0160 g000uu7558 g000uu7559 g000uu2022
        '''#верховный некромант
        '''g000uu8219 g000uu8223
        '''#длань мортис мумификатор
        '''g000uu2008 g000uu2007 g000uu7528
        '''#проповедник
        '''g000uu2021
        '''#элементаль воды
        '''g000uu7536 g002uu5026        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SingleUnits() As String
            Get
                Return ResourceManager.GetString("SingleUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R.
        '''</summary>
        Friend ReadOnly Property spellRandomRace() As String
            Get
                Return ResourceManager.GetString("spellRandomRace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''Строка без пробелов, табов и знаков равенства. Идентификатор локации (ID). На карте названия локаций для размещения отрядов должны состоять из ID, знака подчеркивания и любого символа(ов). Примеры:$newline$В файле: MyLocId ; На карте (одна локация): MyLocId_A$newline$В файле: Тир2_1 ; На карте (две локации): Тир2_1_A Тир2_1_B$newline$В файле: Kraken ; На карте (три локации): Kraken_LegionLoc Kraken_ClanLoc Kraken_CommonLoc
        '''ID
        '''Целое число. Юниты с этой планкой [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StackStatsFields() As String
            Get
                Return ResourceManager.GetString("StackStatsFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map generator by Norvezskaya Semga
        '''
        '''#строка, начинающаяся с решетки, игнорируется
        '''#параметры и их значения не чувствительны к регистру
        '''#разделитель - пробел или табуляция (может идти несколько подряд)
        '''
        '''#внутри блоков настройки могут идти в любом порядке
        '''#порядок блоков тоже может быть любым с одним исключением:
        '''#блоки Location для расовых локаций должны стоять выше, чем блоки для обычных локаций (независимо от genMode)
        '''
        '''#если в блоке Location параметр имеет два значения, то при генерации будет выб [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property template_48x48_unsymm_simple() As String
            Get
                Return ResourceManager.GetString("template_48x48_unsymm_simple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creation_settings.
        '''</summary>
        Friend ReadOnly Property template_creation() As String
            Get
                Return ResourceManager.GetString("template_creation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to header.
        '''</summary>
        Friend ReadOnly Property template_header_keyword() As String
            Get
                Return ResourceManager.GetString("template_header_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location.
        '''</summary>
        Friend ReadOnly Property template_location() As String
            Get
                Return ResourceManager.GetString("template_location", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common_map_settings.
        '''</summary>
        Friend ReadOnly Property template_map() As String
            Get
                Return ResourceManager.GetString("template_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //.
        '''</summary>
        Friend ReadOnly Property template_new_Block() As String
            Get
                Return ResourceManager.GetString("template_new_Block", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Random.
        '''</summary>
        Friend ReadOnly Property template_RandomRaceLongKeyword() As String
            Get
                Return ResourceManager.GetString("template_RandomRaceLongKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R.
        '''</summary>
        Friend ReadOnly Property template_RandomRaceShortKeyword() As String
            Get
                Return ResourceManager.GetString("template_RandomRaceShortKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReadFromFile.
        '''</summary>
        Friend ReadOnly Property template_read_from_file() As String
            Get
                Return ResourceManager.GetString("template_read_from_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %testfile%.
        '''</summary>
        Friend ReadOnly Property testFileKeyword() As String
            Get
                Return ResourceManager.GetString("testFileKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#разделители полей: пробел, таб, знак равенства
        '''#идущие подряд разделители интерпретируются как один
        '''ID location1 AverageExpBar = 1000	ExpStackKilled 200  Race=U StackSize 1 MaxGiants 0		MeleeSlots 2 LootCost 0
        '''AverageExpBar = 100 ID testloc2 StackSize 3 MaxGiants 1		MeleeSlots -1 LootCost 3400 	ExpStackKilled 200  Race=U+d
        '''ID=loc3 AverageExpBar = 1000 Race=HuMans StackSize 1 MeleeSlots 2 LootCost 0	ExpStackKilled 200   MaxGiants 0
        '''ID=loc54 AverageExpBar = [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestStackStats() As String
            Get
                Return ResourceManager.GetString("TestStackStats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#файл, определяющий расу некоторых юнитов независимо от файлов игры
        '''#ID юнита, имя юнита без пробелов и табов, раса
        '''g000uu6010	Гидра	A
        '''g000uu6110	Гидра	A
        '''g000uu6016	Мантикора	A
        '''g000uu6116	Мантикора	A
        '''g000uu8270	Серный_змей	A
        '''g001uu8270	Серный_змей	A
        '''g000uu8218	Волхв	C
        '''g000uu8222	Волхв	C
        '''g000uu8221	Ледяной_кузнец	C
        '''g000uu8226	Сын_Земли	C
        '''g000uu8243	Жрец_Имира	C
        '''g001uu8259	Колосс	C
        '''g000uu8259	Колосс	C
        '''g000uu8266	Дроттар	C
        '''g000uu7500	Гримтурс	C
        '''g0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UnitRace() As String
            Get
                Return ResourceManager.GetString("UnitRace", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
