'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RandomStackGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.1.
        '''</summary>
        Friend ReadOnly Property defaultSigma() As String
            Get
                Return ResourceManager.GetString("defaultSigma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#ID юнитов
        '''#лидеры империи
        '''g000uu0019
        '''g000uu0020
        '''g000uu0021
        '''g000uu0022
        '''g000uu8248
        '''#лидеры кланов
        '''g000uu0044
        '''g000uu0045
        '''g000uu0046
        '''g000uu0047
        '''g000uu8249
        '''#лидеры легионов
        '''g000uu0070
        '''g000uu0071
        '''g000uu0072
        '''g000uu0073
        '''g000uu8250
        '''#лидеры нежити
        '''g000uu0096
        '''g000uu0097
        '''g000uu0098
        '''g000uu0099
        '''g000uu8252
        '''g000uu8253
        '''#лидеры эльфов
        '''g000uu8009
        '''g000uu8010
        '''g000uu8011
        '''g000uu8012
        '''g000uu8251
        '''
        '''#стражи столиц
        '''g000uu3001
        '''g000uu3002
        '''g000uu3003
        '''g000uu3004
        '''g000uu8040
        '''
        '''#призыватели
        '''#учени [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExcludeIDs() As String
            Get
                Return ResourceManager.GetString("ExcludeIDs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #волк
        '''g000uu5039
        '''g000uu5139
        '''#псина
        '''g000uu7533
        '''g006uu1030
        '''#вор
        '''g000uu0023
        '''g000uu0048
        '''g000uu0074
        '''g000uu0100
        '''g000uu8013
        '''g001uu0023
        '''g001uu0048
        '''g001uu0074
        '''g001uu0100
        '''g001uu8013
        '''g000uu5300
        '''g000uu5301
        '''g000uu5302
        '''g000uu5303
        '''g000uu5304
        '''#головорез
        '''g000uu5031
        '''g000uu5131
        '''#разбойник
        '''g000uu5030
        '''g000uu5130
        '''#крестьяник
        '''g000uu5001
        '''g000uu5101
        '''#толстый бес
        '''g000uu6004
        '''g000uu6104
        '''.
        '''</summary>
        Friend ReadOnly Property ExcludeIDsForNames() As String
            Get
                Return ResourceManager.GetString("ExcludeIDsForNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.3.
        '''</summary>
        Friend ReadOnly Property expBarDispersion() As String
            Get
                Return ResourceManager.GetString("expBarDispersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property giantUnitsExpMultiplicator() As String
            Get
                Return ResourceManager.GetString("giantUnitsExpMultiplicator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Идентификаторы типов предметов.
        '''0	nonattack_artefact
        '''1	relic
        '''2	attack_artefact
        '''3	banner
        '''4	elixir
        '''5	healing_elixir
        '''6	ressurection_elixir
        '''7	permanent_elixir
        '''8	scroll
        '''9	stuff
        '''10	jewel
        '''11	sphere
        '''12	talisman
        '''13	boots
        '''14	special
        '''.
        '''</summary>
        Friend ReadOnly Property Items() As String
            Get
                Return ResourceManager.GetString("Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property JewelItemsCostMultiplicator() As String
            Get
                Return ResourceManager.GetString("JewelItemsCostMultiplicator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property lootCostDispersion() As String
            Get
                Return ResourceManager.GetString("lootCostDispersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g000LR0001	H
        '''g000LR0002	H
        '''g000LR0003	H
        '''g000LR0004	C
        '''g000LR0005	C
        '''g000LR0006	C
        '''g000LR0007	L
        '''g000LR0008	L
        '''g000LR0009	L
        '''g000LR0010	U
        '''g000LR0011	U
        '''g000LR0012	U
        '''g000LR0016	E
        '''g000LR0017	E
        '''g000LR0018	E
        '''.
        '''</summary>
        Friend ReadOnly Property Lords() As String
            Get
                Return ResourceManager.GetString("Lords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Первый столбец - идентификаторы объектов.
        '''#В остальных - допустимые места расстановки объектов и расы
        '''
        '''#здания
        '''g000mg0001	G	H C E N S
        '''g000mg0002	G	C
        '''g000mg0003	G	H N S
        '''g000mg0004	G	L
        '''g000mg0005	G	L
        '''g000mg0006	G	H L C U E N S
        '''g000mg0007	G	H L C U E N S
        '''g000mg0008	G	H L C U E N S
        '''g000mg0009	G	H L C U E N S
        '''g000mg0010	G	H L C U E N S
        '''g000mg0011	G	H L C U E N S
        '''g000mg0012	G	H L C U E N S
        '''g000mg0013	G	H L C U E N S
        '''g000mg0014	G	H L C U E N S
        '''g000m [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MapObjectRace() As String
            Get
                Return ResourceManager.GetString("MapObjectRace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gold.
        '''</summary>
        Friend ReadOnly Property mineTypeGold() As String
            Get
                Return ResourceManager.GetString("mineTypeGold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to randmana.
        '''</summary>
        Friend ReadOnly Property mineTypeRandomMana() As String
            Get
                Return ResourceManager.GetString("mineTypeRandomMana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t1mana.
        '''</summary>
        Friend ReadOnly Property mineTypeT1Mana() As String
            Get
                Return ResourceManager.GetString("mineTypeT1Mana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t3mana.
        '''</summary>
        Friend ReadOnly Property mineTypeT3Mana() As String
            Get
                Return ResourceManager.GetString("mineTypeT3Mana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend ReadOnly Property minLocationRadiusAtAll() As String
            Get
                Return ResourceManager.GetString("minLocationRadiusAtAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property nonJewelItemsCostMultiplicator() As String
            Get
                Return ResourceManager.GetString("nonJewelItemsCostMultiplicator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000MAGE.
        '''</summary>
        Friend ReadOnly Property objKeyMage() As String
            Get
                Return ResourceManager.GetString("objKeyMage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000MERC.
        '''</summary>
        Friend ReadOnly Property objKeyMercenaries() As String
            Get
                Return ResourceManager.GetString("objKeyMercenaries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000MERH.
        '''</summary>
        Friend ReadOnly Property objKeyMerchant() As String
            Get
                Return ResourceManager.GetString("objKeyMerchant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MOMNE.
        '''</summary>
        Friend ReadOnly Property objKeyMountain() As String
            Get
                Return ResourceManager.GetString("objKeyMountain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000RU.
        '''</summary>
        Friend ReadOnly Property objKeyRuin() As String
            Get
                Return ResourceManager.GetString("objKeyRuin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G000SI0000TRAI.
        '''</summary>
        Friend ReadOnly Property objKeyTrainer() As String
            Get
                Return ResourceManager.GetString("objKeyTrainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Первый столбец - идентификаторы объектов.
        '''#В остальных - как скреплять объекты
        '''#U = 1/-1 1/0
        '''#D = 1/2 1/3
        '''#L = -1/1 0/1
        '''#R = 2/1 3/1
        '''#B - должна быть граница карты (указывается только одна точка, которая не находится в углу объекта)
        '''#UB = 1/0
        '''#DB = 1/2
        '''#LB = 0/1
        '''#RB = 2/1
        '''#W = водопад
        '''
        '''#обычные
        '''g000mg0008	U L
        '''g000mg0010	L R
        '''g000mg0013	U D
        '''g000mg0060	D R
        '''g000mg0063	U L
        '''
        '''#затычки
        '''g000mg0009	R
        '''g000mg0011	L
        '''g000mg0061	U
        '''g000mg0062	D
        '''g000mg [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PlateauConstructor() As String
            Get
                Return ResourceManager.GetString("PlateauConstructor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#Идентификаторы рас.
        '''#В конце каждой строки ID, на который будут заменяться все остальные ID стртоки
        '''Humans			H	6	1
        '''Undead			U	2
        '''Legions			L	3
        '''Clans			C	K	4
        '''Elves			E	7	14
        '''Neutral			N	5
        '''Greenskins		G	O	8
        '''Dragons			D	9
        '''Swamp			S	10
        '''Water			W	11
        '''Barbarians		B	12
        '''Animals			A	13
        '''AnimalSpider	AS	15
        '''AnimalSnowTerr	AST	16
        '''AnimalWolf		AW	18
        '''AnimalGriffin	AG	19
        '''.
        '''</summary>
        Friend ReadOnly Property Races() As String
            Get
                Return ResourceManager.GetString("Races", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %default%.
        '''</summary>
        Friend ReadOnly Property readDefaultFileKeyword() As String
            Get
                Return ResourceManager.GetString("readDefaultFileKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property smallUnitsExpMultiplicator() As String
            Get
                Return ResourceManager.GetString("smallUnitsExpMultiplicator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''Строка без пробелов, табов и знаков равенства. Идентификатор локации (ID). На карте названия локаций для размещения отрядов должны состоять из ID, знака подчеркивания и любого символа(ов). Примеры:$newline$В файле: MyLocId ; На карте (одна локация): MyLocId_A$newline$В файле: Тир2_1 ; На карте (две локации): Тир2_1_A Тир2_1_B$newline$В файле: Kraken ; На карте (три локации): Kraken_LegionLoc Kraken_ClanLoc Kraken_CommonLoc
        '''ID
        '''Целое число. Юниты с этой планкой оп [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StackStatsFields() As String
            Get
                Return ResourceManager.GetString("StackStatsFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %testfile%.
        '''</summary>
        Friend ReadOnly Property testFileKeyword() As String
            Get
                Return ResourceManager.GetString("testFileKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ITEM_CAT	ITEM_ID	VALUE
        '''6	G000IG0001	g0400:r0000:y0000:e0000:w0000
        '''4	G000IG0002	g0200:r0000:y0000:e0000:w0000
        '''4	G000IG0003	g0450:r0000:y0000:e0000:w0000
        '''7	G000IG0004	g1500:r0000:y0000:e0000:w0000
        '''5	G000IG0005	g0150:r0000:y0000:e0000:w0000
        '''5	G000IG0006	g0300:r0000:y0000:e0000:w0000
        '''7	G000IG0007	g1500:r0000:y0000:e0000:w0000
        '''4	G000IG0008	g0200:r0000:y0000:e0000:w0000
        '''4	G000IG0009	g0450:r0000:y0000:e0000:w0000
        '''7	G000IG0010	g1500:r0000:y0000:e0000:w0000
        '''4	G000IG0011	g0200:r0000:y0000:e0000:w0000
        '''4	G000IG0012	g04 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestItemsTable() As String
            Get
                Return ResourceManager.GetString("TestItemsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LMARK_ID	CX	CY
        '''g000mg0004	1	1
        '''g000mg0005	1	1
        '''g000mg0006	3	3
        '''g000mg0007	3	3
        '''g000mg0008	3	3
        '''g000mg0009	3	3
        '''g000mg0010	3	3
        '''g000mg0011	3	3
        '''g000mg0012	3	3
        '''g000mg0013	3	3
        '''g000mg0014	3	3
        '''g000mg0015	1	1
        '''g000mg0016	1	1
        '''g000mg0017	1	1
        '''g000mg0018	1	1
        '''g000mg0019	1	1
        '''g000mg0020	2	2
        '''g000mg0021	2	2
        '''g000mg0022	1	1
        '''g000mg0023	1	1
        '''g000mg0024	2	2
        '''g000mg0031	1	1
        '''g000mg0032	1	1
        '''g000mg0036	1	1
        '''g000mg0037	1	1
        '''g000mg0038	1	1
        '''g000mg0039	1	1
        '''g000mg0040	1	1
        '''g000mg0046	2	2
        '''g000mg0047	2	2
        '''g000mg0048	2	2
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestObjectSize() As String
            Get
                Return ResourceManager.GetString("TestObjectSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#разделители полей: пробел, таб, знак равенства
        '''#идущие подрядразделители интерпретируются как один
        '''ID location1 AverageExpBar = 1000	ExpStackKilled 200  Race=U StackSize 1 MaxGiants 0		MeleeSlots 2 LootCost 0
        '''AverageExpBar = 100 ID testloc2 StackSize 3 MaxGiants 1		MeleeSlots -1 LootCost 3400 	ExpStackKilled 200  Race=U+d
        '''ID=loc3 AverageExpBar = 1000 Race=HuMans StackSize 1 MeleeSlots 2 LootCost 0	ExpStackKilled 200   MaxGiants 0
        '''ID=loc54 AverageExpBar = 1000 R [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestStackStats() As String
            Get
                Return ResourceManager.GetString("TestStackStats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNIT_ID	UNIT_CAT	LEVEL	SUBRACE	BRANCH	SIZE_SMALL	ATTACK_ID	XP_KILLED	XP_NEXT	LEADERSHIP	WATER_ONLY	REACH
        '''g000uu0001	0	1	1	0	True	g000aa0001	20	80	0	False	3
        '''g000uu0002	0	2	1	0	True	g000aa0002	60	475	0	False	3
        '''g000uu0003	0	3	1	0	True	g000aa0003	120	950	0	False	3
        '''g000uu0004	0	2	1	0	True	g000aa0004	60	475	0	False	3
        '''g000uu0005	0	3	1	0	True	g000aa0005	115	950	0	False	3
        '''g000uu0006	0	1	1	1	True	g000aa0006	20	70	0	False	2
        '''g000uu0007	0	2	1	1	True	g000aa0007	60	500	0	False	2
        '''g000uu0008	0	1	1	2	True	g000aa0008	15	75	0	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestUnitsTable() As String
            Get
                Return ResourceManager.GetString("TestUnitsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #строка, начинающаяся с решетки, игнорируется
        '''#файл, определяющий расу некоторых юнитов независимо от файлов игры
        '''#ID юнита, имя юнита без пробелов и табов, раса
        '''g000uu6010	Гидра	A
        '''g000uu6110	Гидра	A
        '''g000uu6016	Мантикора	A
        '''g000uu6116	Мантикора	A
        '''g000uu8270	Серный_змей	A
        '''g001uu8270	Серный_змей	A
        '''g000uu8218	Волхв	C
        '''g000uu8222	Волхв	C
        '''g000uu8221	Ледяной_кузнец	C
        '''g000uu8226	Сын_Земли	C
        '''g000uu8243	Жрец_Имира	C
        '''g001uu8259	Колосс	C
        '''g000uu8259	Колосс	C
        '''g000uu8266	Дроттар	C
        '''g000uu7500	Гримтурс	C
        '''g0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UnitRace() As String
            Get
                Return ResourceManager.GetString("UnitRace", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
