'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ImpenetrableMeshShow.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #по одной сумке на строку
        '''G000IG1004 G000IG1004 G000IG1003 G000IG1005 G000IG1008 G000IG1007
        '''G000IG0013 G000IG0010
        '''G000IG5015 G000IG5019 G000IG5025 G000IG5009
        '''G000IG7005 G000IG7006 G000IG7009
        '''G000IG7005 G000IG7006 G000IG7009 G000IG6011
        '''G000IG0021 G000IG0022 G000IG0024
        '''G000IG4006 G000IG4007
        '''G000IG8003 G000IG8004 G000IG8005
        '''G000IG9039 G000IG9040
        '''G000IG7115 G000IG7116 G000IG7117 G000IG7118
        '''G000IG9041 G000IG7101
        '''G001IG0047 G001IG0043
        '''G001IG0100 G001IG0102
        '''G000IG0001 G000IG0002
        '''G000IG0009 G000IG000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestBags() As String
            Get
                Return ResourceManager.GetString("TestBags", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
