'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ImpenetrableMeshShow.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATT_ID	NAME_TXT	DESC_TXT	INITIATIVE	SOURCE	CLASS	POWER	REACH	QTY_HEAL	QTY_DAM	LEVEL	ALT_ATTACK	INFINITE	QTY_WARDS	WARD1	WARD2	WARD3	WARD4	CRIT_HIT
        '''g000aa0001	x000tg5001	x000tg5001	50	0	1	80	3	0	25	0	g000000000	False	0	g000000000	g000000000	g000000000	g000000000	False
        '''g000aa0002	x000tg5002	x000tg5002	50	0	1	80	3	0	50	0	g000000000	False	0	g000000000	g000000000	g000000000	g000000000	False
        '''g000aa0003	x000tg5003	x000tg5003	50	0	1	80	3	0	75	0	g000000000	False	0	g000000000	g000000000	g000000000	g000000000	False [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestAttacksTable() As String
            Get
                Return ResourceManager.GetString("TestAttacksTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #по одной сумке на строку
        '''G000IG1004 G000IG1004 G000IG1003 G000IG1005 G000IG1008 G000IG1007
        '''G000IG0013 G000IG0010
        '''G000IG5015 G000IG5019 G000IG5025 G000IG5009
        '''G000IG7005 G000IG7006 G000IG7009
        '''G000IG7005 G000IG7006 G000IG7009 G000IG6011
        '''G000IG0021 G000IG0022 G000IG0024
        '''G000IG4006 G000IG4007
        '''G000IG8003 G000IG8004 G000IG8005
        '''G000IG9039 G000IG9040
        '''G000IG7115 G000IG7116 G000IG7117 G000IG7118
        '''G000IG9041 G000IG7101
        '''G001IG0047 G001IG0043
        '''G001IG0100 G001IG0102
        '''.
        '''</summary>
        Friend ReadOnly Property TestBags() As String
            Get
                Return ResourceManager.GetString("TestBags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPGRADE_ID	ENROLL_C	HIT_POINT	ARMOR	REGEN	REVIVE_C	HEAL_C	TRAINING_C	XP_KILLED	XP_NEXT	MOVE	NEGOTIATE	DAMAGE	HEAL	INITIATIVE	POWER
        '''g000DU0001	g0005:r0000:y0000:e0000:w0000	10	0	0	g0000:r0000:y0000:e0000:w0000	g0000:r0000:y0000:e0000:w0000	g0000:r0000:y0000:e0000:w0000	2	0	1	2	3	0	0	1
        '''g000DU0002	g0030:r0000:y0000:e0000:w0000	15	0	0	g0000:r0000:y0000:e0000:w0000	g0000:r0000:y0000:e0000:w0000	g0000:r0000:y0000:e0000:w0000	6	0	0	0	5	0	0	1
        '''g000DU0003	g0085:r0000:y0000:e0000:w0000	10	1	0	g0000:r0000:y0000:e000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestDynUpgr() As String
            Get
                Return ResourceManager.GetString("TestDynUpgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNIT_ID	IMMUNITY	IMMUNECAT
        '''g000uu0024	12	2
        '''g000uu8015	25	2
        '''g000uu0154	12	2
        '''g000uu5354	12	2
        '''g000uu8020	12	2
        '''g000uu5352	25	2
        '''g000uu5367	25	2
        '''g000uu0167	25	2
        '''g000uu5024	25	2
        '''g000uu5124	25	2
        '''g000uu0155	11	2
        '''g000uu0169	11	3
        '''g000uu0097	11	2
        '''g001uu0097	11	2
        '''g000uu8020	11	2
        '''g000uu6002	3	3
        '''g000uu6002	9	3
        '''g000uu6102	3	3
        '''g000uu6102	9	3
        '''g000uu6002	22	3
        '''g000uu6102	22	3
        '''g000uu8001	3	3
        '''g000uu8101	9	3
        '''g000uu8101	3	3
        '''g000uu8001	9	3
        '''g000uu8001	22	3
        '''g000uu8101	22	3
        '''g000uu8002	3	3
        '''g000uu8102	9	3
        '''g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestGImmuCTable() As String
            Get
                Return ResourceManager.GetString("TestGImmuCTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNIT_ID	IMMUNITY	IMMUNECAT
        '''g000uu0000	0	2
        '''g000uu0024	1	2
        '''g000uu0025	6	3
        '''g000uu0085	0	2
        '''g000uu0078	3	2
        '''g000uu0079	3	2
        '''g000uu0082	3	2
        '''g000uu0083	3	2
        '''g000uu0084	3	2
        '''g000uu0087	3	2
        '''g000uu0088	3	2
        '''g000uu0089	3	2
        '''g000uu0091	4	2
        '''g000uu0095	3	2
        '''g000uu0096	3	2
        '''g000uu0098	3	2
        '''g000uu0099	3	2
        '''g000uu0101	3	2
        '''g000uu0103	3	2
        '''g000uu0104	3	2
        '''g000uu0092	0	2
        '''g000uu0097	3	2
        '''g000uu0004	1	2
        '''g000uu0005	1	2
        '''g000uu5033	3	2
        '''g000uu0090	4	2
        '''g000uu0090	5	2
        '''g000uu0090	6	2
        '''g000uu0090	7	2
        '''g000uu0091	5	2
        '''g000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestGImmuTable() As String
            Get
                Return ResourceManager.GetString("TestGImmuTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MODIF_ID	SOURCE
        '''g000um0001	0
        '''g000um0002	3
        '''g000um0003	3
        '''g000um0005	0
        '''g111um9035	0
        '''g000um0011	0
        '''g000um0012	0
        '''g000um0013	3
        '''g000um0016	0
        '''g000um0017	3
        '''g000um0010	0
        '''g000um0018	0
        '''g000um0021	0
        '''g000um0034	3
        '''g000um0023	3
        '''g000um0026	3
        '''g000um0027	1
        '''g000um0022	1
        '''g000um0035	0
        '''g000um0036	3
        '''g000um0039	1
        '''g000um0040	3
        '''g000um0045	0
        '''g000um0053	1
        '''g000um0049	3
        '''g000um0055	3
        '''g000um0050	3
        '''g000um0064	3
        '''g000um0065	0
        '''g000um0069	3
        '''g000um0073	3
        '''g000um0076	3
        '''g000um0075	3
        '''g000um0079	0
        '''g000um2002	0
        '''g000u [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestGModif() As String
            Get
                Return ResourceManager.GetString("TestGModif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BELONGS_TO	DESC	TYPE	PERCENT	NUMBER	ABILITY	IMMUNITY	IMMUNECAT	MOVE	IMMUNITYC	IMMUNECATC
        '''g000um0001	x000tgc001	12	0	0	0	7	2	0	0	0
        '''g000um0002	x000tgc002	9	10	0	0	0	2	0	0	0
        '''g000um0003	x000tgc003	4	10	0	0	0	2	0	0	0
        '''g000um0004	x000tgc004	12	0	0	0	7	2	0	0	0
        '''g000um0005	x000tgc005	12	0	0	0	5	2	0	0	0
        '''g000um0008	x000tgc008	12	0	0	0	5	2	0	0	0
        '''g000um0010	x000tgc010	12	0	0	0	6	2	0	0	0
        '''g000um0012	x000tgc012	5	0	20	0	0	2	0	0	0
        '''g000um0014	x000tgc014	12	0	0	0	1	2	0	0	0
        '''g000um0015	x000tgc015	12	0	0	0	1	2	0	0	0
        '''g0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestGModifL() As String
            Get
                Return ResourceManager.GetString("TestGModifL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ITEM_CAT	ITEM_ID	VALUE
        '''6	G000IG0001	g0400:r0000:y0000:e0000:w0000
        '''4	G000IG0002	g0200:r0000:y0000:e0000:w0000
        '''4	G000IG0003	g0450:r0000:y0000:e0000:w0000
        '''7	G000IG0004	g1500:r0000:y0000:e0000:w0000
        '''5	G000IG0005	g0150:r0000:y0000:e0000:w0000
        '''5	G000IG0006	g0300:r0000:y0000:e0000:w0000
        '''7	G000IG0007	g1500:r0000:y0000:e0000:w0000
        '''4	G000IG0008	g0200:r0000:y0000:e0000:w0000
        '''4	G000IG0009	g0450:r0000:y0000:e0000:w0000
        '''7	G000IG0010	g1500:r0000:y0000:e0000:w0000
        '''4	G000IG0011	g0200:r0000:y0000:e0000:w0000
        '''4	G0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestItemsTable() As String
            Get
                Return ResourceManager.GetString("TestItemsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LMARK_ID	CX	CY
        '''g000mg0004	1	1
        '''g000mg0005	1	1
        '''g000mg0006	3	3
        '''g000mg0007	3	3
        '''g000mg0008	3	3
        '''g000mg0009	3	3
        '''g000mg0010	3	3
        '''g000mg0011	3	3
        '''g000mg0012	3	3
        '''g000mg0013	3	3
        '''g000mg0014	3	3
        '''g000mg0015	1	1
        '''g000mg0016	1	1
        '''g000mg0017	1	1
        '''g000mg0018	1	1
        '''g000mg0019	1	1
        '''g000mg0020	2	2
        '''g000mg0021	2	2
        '''g000mg0022	1	1
        '''g000mg0023	1	1
        '''g000mg0024	2	2
        '''g000mg0031	1	1
        '''g000mg0032	1	1
        '''g000mg0036	1	1
        '''g000mg0037	1	1
        '''g000mg0038	1	1
        '''g000mg0039	1	1
        '''g000mg0040	1	1
        '''g000mg0046	2	2
        '''g000mg0047	2	2
        '''g000mg0048	2	2
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestObjectSize() As String
            Get
                Return ResourceManager.GetString("TestObjectSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPELL_ID	CATEGORY	LEVEL	CASTING_C	AREA
        '''g000ss0001	3	1	g0000:r0000:y0100:e0000:w0000	1
        '''g000ss0002	3	1	g0000:r0000:y0100:e0000:w0000	1
        '''g000ss0003	3	1	g0000:r0000:y0100:e0000:w0000	1
        '''g000ss0004	0	1	g0000:r0000:y0100:e0000:w0000	1
        '''g000ss0005	3	1	g0000:r0000:y0100:e0000:w0000	1
        '''g000ss0006	8	2	g0000:r0000:y0200:e0000:w0000	1
        '''g000ss0007	2	2	g0000:r0000:y0200:e0000:w0000	1
        '''g000ss0008	4	2	g0000:r0000:y0200:e0000:w0000	1
        '''g000ss0009	7	2	g0000:r0000:y0200:e0000:w0000	5
        '''g000ss0011	3	3	g0000:r0000:y0150:e0000:w [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestSpells() As String
            Get
                Return ResourceManager.GetString("TestSpells", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LORD_ID	SPELL_ID	RESEARCH
        '''g000LR0001	g000ss0001	g0000:r0000:y0200:e0000:w0000
        '''g000LR0001	g000ss0002	g0000:r0000:y0200:e0000:w0000
        '''g000LR0001	g000ss0003	g0000:r0000:y0200:e0000:w0000
        '''g000LR0001	g000ss0004	g0000:r0000:y0200:e0000:w0000
        '''g000LR0001	g000ss0005	g0000:r0000:y0200:e0000:w0000
        '''g000LR0001	g000ss0006	g0000:r0000:y0400:e0000:w0000
        '''g000LR0001	g000ss0007	g0000:r0000:y0400:e0000:w0000
        '''g000LR0001	g000ss0008	g0000:r0000:y0400:e0000:w0000
        '''g000LR0001	g000ss0009	g0000:r0000:y0400:e0000:w0000
        '''g000LR00 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestSpellsRace() As String
            Get
                Return ResourceManager.GetString("TestSpellsRace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNIT_ID	UNIT_CAT	LEVEL	PREV_ID	RACE_ID	SUBRACE	BRANCH	SIZE_SMALL	SEX_M	ENROLL_C	ENROLL_B	NAME_TXT	DESC_TXT	ABIL_TXT	ATTACK_ID	ATTACK2_ID	ATCK_TWICE	HIT_POINT	BASE_UNIT	ARMOR	REGEN	REVIVE_C	HEAL_C	TRAINING_C	XP_KILLED	UPGRADE_B	XP_NEXT	MOVE	SCOUT	LIFE_TIME	LEADERSHIP	NEGOTIATE	LEADER_CAT	DYN_UPG1	DYN_UPG_LV	DYN_UPG2	WATER_ONLY	DEATH_ANIM
        '''g000uu0001	0	1	g000000000	g000rr0000	1	0	True	True	g0050:r0000:y0000:e0000:w0000	g000000000	x000tg2001	x000tg2501	x000tgb006	g000aa0001	g000000000	False	110	G000000000	0	5	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TestUnitsTable() As String
            Get
                Return ResourceManager.GetString("TestUnitsTable", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
